# Generated by Django 3.2 on 2022-06-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_date']},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=30)),
                ('lesson_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('lesson_status', models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')], default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'ordering': ['-booked_date'],
            },
        ),
    ]
