# Generated by Django 3.2 on 2022-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220602_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='booking',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermedia', 'Intermedium'), ('Advanced', 'Advanced'), ('Examination-training', 'Examination-training')], max_length=30),
        ),
    ]
