# Generated by Django 3.2 on 2022-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220602_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_status', models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')], default=0)),
            ],
        ),
    ]
