# Generated by Django 3.2 on 2022-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
