# Generated by Django 3.2 on 2022-06-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_zzaxtb.jpg', upload_to='profile_image'),
        ),
    ]
