# Generated by Django 3.2 on 2022-06-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
    ]
