# Generated by Django 3.2 on 2022-06-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20220611_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lesson_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Exams-training', 'Exams-training')], max_length=30),
        ),
    ]
