# Generated by Django 3.2 on 2022-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_name',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Exams-training', 'Exams-training'), ('Live-recital', 'Live-recital'), ('Virtual-performance', 'Virtual-performance'), ('Repertoire-recording', 'Repertoire-recording'), ('Online-recital', 'Online-recital'), ('End-of-year-concert', 'End-of-year-concert')], default='Beginner', max_length=30),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
