# Generated by Django 3.2 on 2022-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_booking_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_name',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Exams Training', 'Exams-training'), ('Live Recital', 'Live-recital'), ('Virtual Performance', 'Virtual-performance'), ('Repertoire Recording', 'Repertoire-recording'), ('Online Recital', 'Online-recital'), ('End Of Year Concert', 'End-of-year-concert')], default='Beginner', max_length=30),
        ),
    ]
