# Generated by Django 3.2 on 2022-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_booking_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
