# Generated by Django 3.2 on 2022-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20220624_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
