# Generated by Django 3.2 on 2022-06-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20220624_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_rejected',
        ),
    ]
