# Generated by Django 3.2 on 2022-06-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20220625_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.CharField(choices=[('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00')], default='09:00 - 10:00', max_length=200),
        ),
    ]
