# Generated by Django 3.2 on 2022-06-27 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20220627_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name_profile',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alpha[ A - Z] characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_profile',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alpha[ A - Z] characters are allowed.')]),
        ),
    ]
