# Generated by Django 3.2 on 2022-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_auto_20220628_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_denied',
            field=models.BooleanField(default=False, verbose_name='Denied'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_pending',
            field=models.BooleanField(default=False, verbose_name='Pending'),
        ),
    ]
