# Generated by Django 3.2 on 2022-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20220629_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_approved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_denied',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_pending',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
